### ISSUE TITLE
动画卡顿

### ISSUE THREAD

**Issue by gh138312** [WarmYunyang/BottomTabWithLottieNavigation#1]
当在onresume或之前的声明周期中执行一段初始化（用一个for循环打印log模拟下）动画会出现卡顿，从0-1中间的过度效果没有了。

**Comment by WarmYunyang** [comment]
> 当在onresume或之前的声明周期中执行一段初始化（用一个for循环打印log模拟下）动画会出现卡顿，从0-1中间的过度效果没有了。

**Comment by WarmYunyang** [comment]
> 当在onresume或之前的声明周期中执行一段初始化（用一个for循环打印log模拟下）动画会出现卡顿，从0-1中间的过度效果没有了。

您好，有测试Demo嘛。请联系我邮箱：warmyunyang@foxmail.com

**Comment by gh138312** [comment]
在您TestFragment的声明周期中加入  for(i in 0..50000){
            Log.e("","")
        }
然后您运行一下

**Comment by WarmYunyang** [comment]
> 在您TestFragment的声明周期中加入 for(i in 0..50000){ Log.e("","") } 然后您运行一下

好的，请联系我邮箱：warmyunyang@foxmail.com，加个通讯软件好友。晚上讨论看看的呢。
